server:
  servlet:
    context-path: /crud/best-practice
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carinvoces
    username: carlos
    password: carlos

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        jdbc.lob.non_contextual_creation: true
        enable_lazy_load_no_trans: true
    generate-ddl: false

security:
  jwt:
    token:
      header: Authorization
      prefix: Bearer
      expirationHours: 10
      secretKey: Pa9hWJr3zmtSXL7HxH6GEEfQdiOp9Cdu

