#!/usr/bin/env groovy
pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        disableConcurrentBuilds()
        timeout(time: 1, unit: 'HOURS')
        timestamps()
    }

    tools {
        jdk 'Java JDK 8u221'
        maven 'maven 3.6.3'
    }

    environment {
        IS_SNAPSHOT = readMavenPom().getVersion().endsWith("-SNAPSHOT")
    }

    stages {
        stage('Build') {
            steps {
                sh "mvn -B -U clean package"
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            deleteDir()
        }
    }
}
